### ISSUE TITLE
Segmentation fault at PySet_Discard

### ISSUE THREAD

**Issue by RobertoPrevato** [RobertoPrevato/BlackSheep#2]
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
PySet_Discard (set=set@entry=0x0, key=key@entry=0x7fffeee1a2a8) at Objects/setobject.c:2331
2331        if (!PySet_Check(set)) {
```

## More details:
```
#0  PySet_Discard (set=set@entry=0x0, key=key@entry=0x7fffeee1a2a8) at Objects/setobject.c:2331
#1  0x00007fffef8ca077 in __Pyx_PySet_Discard (key=0x7fffeee1a2a8, set=0x0) at blacksheep/connection.c:9544
#2  __pyx_f_10blacksheep_10connection_16ServerConnection_dispose (__pyx_v_self=0x7fffeee1a2a8) at blacksheep/connection.c:3873
#3  0x00007fffef8bd36e in __pyx_pf_10blacksheep_10connection_16ServerConnection_14connection_lost (__pyx_v_exc=<optimized out>, 
    __pyx_v_self=<optimized out>) at blacksheep/connection.c:3574
#4  __pyx_pw_10blacksheep_10connection_16ServerConnection_15connection_lost (__pyx_v_self=<optimized out>, __pyx_v_exc=<optimized out>)
    at blacksheep/connection.c:3561
#5  0x00007fffeff31693 in __Pyx_PyObject_CallMethO (arg=0x555555a48dc0 <_Py_NoneStruct>, func=<optimized out>) at uvloop/loop.c:161546
#6  __Pyx_PyObject_CallOneArg (func=<optimized out>, arg=0x555555a48dc0 <_Py_NoneStruct>) at uvloop/loop.c:30505
#7  0x00007ffff0046257 in __pyx_f_6uvloop_4loop_15UVBaseTransport__call_connection_lost (__pyx_v_self=0x555555e7c2b8, 
    __pyx_v_exc=0x555555a48dc0 <_Py_NoneStruct>) at uvloop/loop.c:83709
#8  0x00007ffff006bd59 in __pyx_f_6uvloop_4loop_6Handle__run (__pyx_v_self=__pyx_v_self@entry=0x7fffef669048) at uvloop/loop.c:57826
```

investigate and resolve.

**Comment by RobertoPrevato** [comment]
Corrected with: https://github.com/RobertoPrevato/BlackSheep/commit/73873f7bdc0250279bd289a0438b7a2f3fc1947e
